import { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Arnau Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-10">
        <h1 className="text-4xl font-bold text-gray-200">
          Hi, I am <span className="text-sky-600">Arnau</span>.{" "}
          <p>I am a Full Stack Developer based in Spain.</p>
        </h1>
        <h1 className="mt-10 w-[17ch] animate-typing overflow-hidden whitespace-nowrap border-r-4 border-r-white pr-5 text-4xl text-white font-bold">
          Wanna know more?
        </h1>
      </main>
    </>
  );
};

export default Home;
